apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tax-calculator-pipeline-run-
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: repo-url
      value: "https://github.com/YOUR_GITHUB_USERNAME/tax-calculator-pipeline.git"
    - name: branch
      value: "main"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tax-calculator-pvc
