apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-task
spec:
  workspaces:
    - name: source
  steps:
    - name: install
      image: node:18
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        npm install
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine-task
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: node:18
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        npx jasmine
